<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260731010000 extends AbstractMigration
{
    public function getDescription(): string { return 'Create final Trade and Promotion-owned schema baseline'; }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE trade_product (id INT AUTO_INCREMENT NOT NULL, uuid VARCHAR(36) NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, is_deleted TINYINT(1) NOT NULL, metadata JSON DEFAULT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX uniq_trade_product_uuid (uuid), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE trade_specification (id INT AUTO_INCREMENT NOT NULL, product_id INT NOT NULL, uuid VARCHAR(36) NOT NULL, name VARCHAR(255) NOT NULL, price BIGINT NOT NULL, status VARCHAR(20) NOT NULL, sort INT NOT NULL, is_deleted TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX uniq_trade_specification_uuid (uuid), INDEX IDX_TRADE_SPECIFICATION_PRODUCT (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB");
        $this->addSql('ALTER TABLE trade_specification ADD CONSTRAINT FK_TRADE_SPECIFICATION_PRODUCT FOREIGN KEY (product_id) REFERENCES trade_product (id) ON DELETE CASCADE');
        $this->addSql("CREATE TABLE trade_order (id INT AUTO_INCREMENT NOT NULL, uuid VARCHAR(36) NOT NULL, user_uuid VARCHAR(36) DEFAULT NULL, total_amount BIGINT NOT NULL, currency VARCHAR(10) NOT NULL, status VARCHAR(40) NOT NULL, notes LONGTEXT DEFAULT NULL, metadata JSON DEFAULT NULL, cancelled_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', completed_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', paid_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', refunded_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', fulfilled_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', payment_method VARCHAR(50) DEFAULT NULL, invoice_id VARCHAR(64) DEFAULT NULL, invoice_no VARCHAR(64) DEFAULT NULL, payment_status VARCHAR(30) DEFAULT NULL, tracking_number VARCHAR(100) DEFAULT NULL, shipping_address LONGTEXT DEFAULT NULL, refund_reason LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX uniq_trade_order_uuid (uuid), INDEX idx_trade_order_user_uuid (user_uuid), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE trade_order_item (id INT AUTO_INCREMENT NOT NULL, order_id INT NOT NULL, specification_id INT DEFAULT NULL, uuid VARCHAR(36) NOT NULL, specification_title VARCHAR(255) DEFAULT NULL, quantity INT NOT NULL, unit_price BIGINT NOT NULL, price BIGINT NOT NULL, cost BIGINT NOT NULL, profit BIGINT NOT NULL, spec_snapshot JSON DEFAULT NULL, product_snapshot JSON DEFAULT NULL, metadata JSON DEFAULT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX uniq_trade_order_item_uuid (uuid), INDEX IDX_TRADE_ORDER_ITEM_ORDER (order_id), INDEX IDX_TRADE_ORDER_ITEM_SPECIFICATION (specification_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB");
        $this->addSql('ALTER TABLE trade_order_item ADD CONSTRAINT FK_TRADE_ORDER_ITEM_ORDER FOREIGN KEY (order_id) REFERENCES trade_order (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trade_order_item ADD CONSTRAINT FK_TRADE_ORDER_ITEM_SPECIFICATION FOREIGN KEY (specification_id) REFERENCES trade_specification (id) ON DELETE SET NULL');
        $this->addSql("CREATE TABLE trade_outbox_message (id BIGINT AUTO_INCREMENT NOT NULL, event_id VARCHAR(36) NOT NULL, correlation_id VARCHAR(36) DEFAULT NULL, causation_id VARCHAR(36) DEFAULT NULL, topic VARCHAR(120) NOT NULL, aggregate_type VARCHAR(80) NOT NULL, aggregate_id VARCHAR(64) NOT NULL, payload JSON NOT NULL, occurred_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', available_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', published_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', attempts INT NOT NULL, last_error LONGTEXT DEFAULT NULL, UNIQUE INDEX uniq_trade_outbox_event_id (event_id), INDEX idx_trade_outbox_unpublished_available (published_at, available_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE trade_consumed_event (id BIGINT AUTO_INCREMENT NOT NULL, event_id VARCHAR(36) NOT NULL, topic VARCHAR(120) NOT NULL, aggregate_id VARCHAR(64) NOT NULL, payload_hash VARCHAR(64) NOT NULL, processed_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX uniq_trade_consumed_event_id (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE trade_store_directory (id INT AUTO_INCREMENT NOT NULL, store_uuid VARCHAR(36) NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, status VARCHAR(30) NOT NULL, source_updated_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX uniq_trade_store_directory_uuid (store_uuid), UNIQUE INDEX uniq_trade_store_directory_code (code), INDEX idx_trade_store_directory_code_status (code, status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE promotion_template (id INT AUTO_INCREMENT NOT NULL, uuid VARCHAR(36) NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, type VARCHAR(50) NOT NULL, phase INT NOT NULL, enabled TINYINT(1) NOT NULL, dsl LONGTEXT NOT NULL, fields JSON DEFAULT NULL, ast_cache JSON DEFAULT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX uniq_promotion_template_uuid (uuid), UNIQUE INDEX UNIQ_PROMOTION_TEMPLATE_NAME (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE promotion (id INT AUTO_INCREMENT NOT NULL, template_id INT NOT NULL, uuid VARCHAR(36) NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, store_code VARCHAR(50) NOT NULL, enabled TINYINT(1) NOT NULL, start_time DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', end_time DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', config JSON DEFAULT NULL, conflict_mode VARCHAR(30) NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX uniq_promotion_uuid (uuid), UNIQUE INDEX UNIQ_PROMOTION_NAME (name), INDEX IDX_PROMOTION_TEMPLATE (template_id), INDEX IDX_PROMOTION_ACTIVE_STORE (store_code, enabled, start_time, end_time), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB");
        $this->addSql('ALTER TABLE promotion ADD CONSTRAINT FK_PROMOTION_TEMPLATE FOREIGN KEY (template_id) REFERENCES promotion_template (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        foreach (['promotion', 'promotion_template', 'trade_store_directory', 'trade_consumed_event', 'trade_outbox_message', 'trade_order_item', 'trade_order', 'trade_specification', 'trade_product'] as $table) { $this->addSql('DROP TABLE ' . $table); }
    }
}
