services:
    _instanceof:
        App\Promotion\Strategy\PromotionStrategyInterface:
            tags: ['promotion.strategy']

    App\Promotion\Service\Dsl\:
        resource: '../../Service/Dsl/'

    App\Promotion\Strategy\:
        resource: '../../Strategy/'
