controllers:
    resource: routing.controllers

api_common:
    prefix: /api/v1
    resource:
        path: ../src/Common/Controller/
        namespace: App\Common\Controller
    type: attribute

api_trade:
    prefix: /api/v1
    resource:
        path: ../src/Trade/Controller/
        namespace: App\Trade\Controller
    type: attribute

api_wallet:
    prefix: /api/v1
    resource:
        path: ../vendor/crud-platform/wallet-app/src/Controller/
        namespace: App\Wallet\Controller
    type: attribute

api_payment_app:
    prefix: /api/v1
    resource:
        path: ../vendor/crud-platform/payment-app/src/Controller/App/
        namespace: App\Payment\Controller\App
    type: attribute

api_payment_manage:
    prefix: /api/v1
    resource:
        path: ../vendor/crud-platform/payment-app/src/Controller/Manage/
        namespace: App\Payment\Controller\Manage
    type: attribute

payment_webhook:
    resource:
        path: ../vendor/crud-platform/payment-app/src/Controller/Webhook/
        namespace: App\Payment\Controller\Webhook
    type: attribute

api_identity_app:
    prefix: /api/v1
    resource:
        path: ../src/Identity/Controller/App/
        namespace: App\Identity\Controller\App
    type: attribute

api_identity_manage:
    prefix: /api/v1
    resource:
        path: ../src/Identity/Controller/Manage/
        namespace: App\Identity\Controller\Manage
    type: attribute

wechat:
    resource:
        path: ../src/Wechat/Controller/
        namespace: App\Wechat\Controller
    type: attribute

wechat_app:
    prefix: /api/v1
    resource:
        path: ../src/Wechat/Controller/App/
        namespace: App\Wechat\Controller\App
    type: attribute

wechat_manage:
    prefix: /api/v1
    resource:
        path: ../src/Wechat/Controller/Manage/
        namespace: App\Wechat\Controller\Manage
    type: attribute

api_promotion:
    prefix: /api/v1
    resource:
        path: ../src/Promotion/Controller/
        namespace: App\Promotion\Controller
    type: attribute

api_store:
    prefix: /api/v1
    resource:
        path: ../vendor/crud-platform/store-app/src/Controller/
        namespace: App\Store\Controller
    type: attribute

api_inventory:
    prefix: /api/v1
    resource:
        path: ../vendor/crud-platform/inventory-app/src/Controller/
        namespace: App\Inventory\Controller
    type: attribute
