controllers:
    resource: routing.controllers

api_common:
    prefix: /api/v1
    resource:
        path: ../src/Common/Controller/
        namespace: App\Common\Controller
    type: attribute

api_trade:
    prefix: /api/v1
    resource:
        path: ../src/Trade/Controller/
        namespace: App\Trade\Controller
    type: attribute

api_wallet:
    prefix: /api/v1
    resource:
        path: ../vendor/crud-platform/wallet-app/src/Controller/
        namespace: App\Wallet\Controller
    type: attribute

api_payment_app:
    prefix: /api/v1
    resource:
        path: ../vendor/crud-platform/payment-app/src/Controller/App/
        namespace: App\Payment\Controller\App
    type: attribute

api_payment_manage:
    prefix: /api/v1
    resource:
        path: ../vendor/crud-platform/payment-app/src/Controller/Manage/
        namespace: App\Payment\Controller\Manage
    type: attribute

payment_webhook:
    resource:
        path: ../vendor/crud-platform/payment-app/src/Controller/Webhook/
        namespace: App\Payment\Controller\Webhook
    type: attribute

api_identity_app:
    prefix: /api/v1
    resource:
        path: ../vendor/crud-platform/identity-app/src/Main/Controller/App/
        namespace: App\Identity\Main\Controller\App
    type: attribute

api_identity_manage:
    prefix: /api/v1
    resource:
        path: ../vendor/crud-platform/identity-app/src/Main/Controller/Manage/
        namespace: App\Identity\Main\Controller\Manage
    type: attribute

wechat:
    resource:
        path: ../vendor/crud-platform/identity-app/src/Wechat/Controller/LoginController.php
        namespace: App\Identity\Wechat\Controller
    type: attribute

wechat_app:
    prefix: /api/v1
    resource:
        path: ../vendor/crud-platform/identity-app/src/Wechat/Controller/App/
        namespace: App\Identity\Wechat\Controller\App
    type: attribute

wechat_manage:
    prefix: /api/v1
    resource:
        path: ../vendor/crud-platform/identity-app/src/Wechat/Controller/Manage/
        namespace: App\Identity\Wechat\Controller\Manage
    type: attribute

identity_auth:
    resource:
        path: ../vendor/crud-platform/identity-app/src/Main/Controller/AuthController.php
        namespace: App\Identity\Main\Controller
    type: attribute

identity_otp:
    resource:
        path: ../vendor/crud-platform/identity-app/src/Main/Controller/OtpController.php
        namespace: App\Identity\Main\Controller
    type: attribute

api_promotion:
    prefix: /api/v1
    resource:
        path: ../src/Promotion/Controller/
        namespace: App\Promotion\Controller
    type: attribute

api_store:
    prefix: /api/v1
    resource:
        path: ../vendor/crud-platform/store-app/src/Controller/
        namespace: App\Store\Controller
    type: attribute

api_inventory:
    prefix: /api/v1
    resource:
        path: ../vendor/crud-platform/inventory-app/src/Controller/
        namespace: App\Inventory\Controller
    type: attribute
