parameters: {}
services:
    _defaults: { autowire: true, autoconfigure: true }
    _instanceof:
        App\Core\Controller\RestController:
            calls:
                - [ setRequestStack, [ '@request_stack' ] ]
                - [ setSerializer, [ '@serializer' ] ]
                - [ setTranslator, [ '@translator' ] ]
                - [ setServiceContainer, [ '@service_container' ] ]
    App\Wallet\:
        resource: '../src/'
        exclude: [ '../src/Kernel.php' ]
    App\Core\:
        resource: '../vendor/crud-platform/platform-kernel/src/'
        exclude:
            - '../vendor/crud-platform/platform-kernel/src/Serializer/Normalizer/FlatNormalizer.php'
            - '../vendor/crud-platform/platform-kernel/src/EventListener/*'
    App\Core\Service\ServiceLocatorInterface: '@App\Core\Service\DefaultServiceLocator'
    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'
