<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
final class Version20260730000000 extends AbstractMigration {
    public function getDescription(): string { return 'Create final Wallet-owned schema baseline'; }
    public function up(Schema $schema): void {
        $this->addSql("CREATE TABLE wallet (id INT AUTO_INCREMENT NOT NULL, owner_uuid VARCHAR(36) NOT NULL, currency VARCHAR(10) NOT NULL, balance BIGINT NOT NULL, version INT NOT NULL, status VARCHAR(20) NOT NULL, label VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', updated_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX uniq_wallet_owner_uuid_currency (owner_uuid, currency), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE wallet_transaction (id INT AUTO_INCREMENT NOT NULL, uuid VARCHAR(36) NOT NULL, from_wallet_id INT DEFAULT NULL, to_wallet_id INT DEFAULT NULL, amount BIGINT NOT NULL, type VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, reference_id VARCHAR(64) DEFAULT NULL, description LONGTEXT DEFAULT NULL, metadata LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', completed_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX uniq_wallet_tx_uuid (uuid), UNIQUE INDEX uniq_wallet_tx_reference (reference_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB");
        $this->addSql('ALTER TABLE wallet_transaction ADD CONSTRAINT fk_wallet_tx_from FOREIGN KEY (from_wallet_id) REFERENCES wallet (id) ON DELETE SET NULL, ADD CONSTRAINT fk_wallet_tx_to FOREIGN KEY (to_wallet_id) REFERENCES wallet (id) ON DELETE SET NULL');
        $this->addSql("CREATE TABLE wallet_payment_deduction (id INT AUTO_INCREMENT NOT NULL, uuid VARCHAR(36) NOT NULL, invoice_id VARCHAR(36) NOT NULL, invoice_no VARCHAR(64) NOT NULL, payer_id INT NOT NULL, wallet_id INT NOT NULL, system_wallet_id INT NOT NULL, type VARCHAR(30) NOT NULL, amount BIGINT NOT NULL, currency VARCHAR(10) NOT NULL, status VARCHAR(30) NOT NULL, wallet_transaction_id VARCHAR(64) DEFAULT NULL, reversal_transaction_id VARCHAR(64) DEFAULT NULL, reference_id VARCHAR(64) NOT NULL, metadata JSON DEFAULT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', applied_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', released_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', refunded_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', UNIQUE INDEX uniq_wallet_payment_deduction_uuid (uuid), UNIQUE INDEX uniq_wallet_payment_deduction_reference (reference_id), UNIQUE INDEX uniq_wallet_payment_deduction_invoice_type (invoice_id, type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB");
    }
    public function down(Schema $schema): void { $this->addSql('DROP TABLE wallet_payment_deduction'); $this->addSql('DROP TABLE wallet_transaction'); $this->addSql('DROP TABLE wallet'); }
}
