services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Wechat\Service\Payment\WechatPayService:
        arguments:
            $miniappAppId: '%env(WECHAT_MINIAPP_APP_ID)%'
            $miniappSecret: '%env(WECHAT_MINIAPP_SECRET)%'
            $payMchId: '%env(WECHAT_PAY_MCH_ID)%'
            $paySecretKey: '%env(WECHAT_PAY_SECRET_KEY)%'
            $payPrivateKeyPath: '%env(WECHAT_PAY_PRIVATE_KEY)%'
            $payCertificatePath: '%env(WECHAT_PAY_CERTIFICATE)%'
            $payPlatformCertPath: '%env(WECHAT_PAY_PLATFORM_CERT)%'
            $payPubKeyId: '%env(WECHAT_PAY_PUB_KEY_ID)%'
            $payPubKeyPath: '%env(WECHAT_PAY_PUB_KEY_PATH)%'

    App\Wechat\Service\Payment\WechatPayGateway:
        arguments:
            $notifyUrl: '%env(WECHAT_PAY_NOTIFY_URL)%'
        tags: ['payment.gateway']
