parameters: {}

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Core\Controller\RestController:
            calls:
                - [ setRequestStack, [ '@request_stack' ] ]
                - [ setSerializer, [ '@serializer' ] ]
                - [ setTranslator, [ '@translator' ] ]
                - [ setServiceContainer, [ '@service_container' ] ]

    App\Store\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Core\:
        resource: '../vendor/crud-platform/platform-kernel/src/'
        exclude:
            - '../vendor/crud-platform/platform-kernel/src/Serializer/Normalizer/FlatNormalizer.php'
            - '../vendor/crud-platform/platform-kernel/src/EventListener/*'

    App\Core\EventListener\ExceptionInterceptor:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
        arguments:
            $translator: '@translator'
            $logger: '@logger'
            $env: '%kernel.environment%'

    App\Core\EventListener\ControllerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        arguments:
            $tokenStorage: '@security.token_storage'
            $logger: '@logger'

    App\Core\Service\ServiceLocatorInterface: '@App\Core\Service\DefaultServiceLocator'
